"""qondor customer — Customer commands."""

from __future__ import annotations

from typing import Annotated

import typer
from qondor_api_sdk.models.customer import CreateCustomer, UpdateCustomer

from .._run import run_async

app = typer.Typer(no_args_is_help=True)


@app.command()
def get(
    id: Annotated[int, typer.Argument(help="Customer ID")],
    subscription_key: Annotated[
        str | None, typer.Option("--subscription-key", "-k", envvar="QONDOR_SUBSCRIPTION_KEY")
    ] = None,
    env: Annotated[str | None, typer.Option("--env", "-e", envvar="QONDOR_ENV")] = None,
    raw: Annotated[bool, typer.Option("--raw", help="Compact JSON")] = False,
) -> None:
    """Get a customer by ID."""
    run_async(lambda c: c.customer.get(id), subscription_key=subscription_key, env=env, raw=raw)


@app.command("list")
def list_customers(
    office_id: Annotated[
        int | None, typer.Option("--office-id", help="Filter by office; null for global customers")
    ] = None,
    subscription_key: Annotated[
        str | None, typer.Option("--subscription-key", "-k", envvar="QONDOR_SUBSCRIPTION_KEY")
    ] = None,
    env: Annotated[str | None, typer.Option("--env", "-e", envvar="QONDOR_ENV")] = None,
    raw: Annotated[bool, typer.Option("--raw", help="Compact JSON")] = False,
) -> None:
    """List customers."""
    run_async(lambda c: c.customer.get_all(office_id=office_id), subscription_key=subscription_key, env=env, raw=raw)


@app.command()
def create(
    name: Annotated[str, typer.Option("--name", help="Customer name")],
    office_id: Annotated[int | None, typer.Option("--office-id", help="Office the customer belongs to")] = None,
    customer_number: Annotated[
        str | None, typer.Option("--customer-number", help="Customer number (may be autogenerated)")
    ] = None,
    external_reference: Annotated[
        str | None, typer.Option("--external-reference", help="Your unique external reference")
    ] = None,
    city: Annotated[str | None, typer.Option("--city", help="City")] = None,
    country_code: Annotated[str | None, typer.Option("--country-code", help="Two-letter ISO country code")] = None,
    organisation_number: Annotated[
        str | None, typer.Option("--organisation-number", help="Organisation number (may be mandatory per office)")
    ] = None,
    legal_name: Annotated[str | None, typer.Option("--legal-name", help="Legal name")] = None,
    address: Annotated[str | None, typer.Option("--address", help="Address line 1")] = None,
    address2: Annotated[str | None, typer.Option("--address2", help="Address line 2")] = None,
    zip_code: Annotated[str | None, typer.Option("--zip-code", help="Zip/postal code")] = None,
    vat_number: Annotated[str | None, typer.Option("--vat-number", help="VAT number")] = None,
    phone_number: Annotated[str | None, typer.Option("--phone-number", help="Phone number")] = None,
    fax_number: Annotated[str | None, typer.Option("--fax-number", help="Fax number")] = None,
    is_invoiceable: Annotated[
        bool | None, typer.Option("--is-invoiceable/--no-is-invoiceable", help="Whether the customer is invoiceable")
    ] = None,
    invoice_currency: Annotated[
        str | None, typer.Option("--invoice-currency", help="Three-letter ISO 4217 code (e.g. EUR, USD, GBP)")
    ] = None,
    invoice_currency_code: Annotated[
        int | None, typer.Option("--invoice-currency-code", help="Numeric ISO 4217 code (e.g. 978=EUR, 840=USD)")
    ] = None,
    invoice_address_enabled: Annotated[
        bool | None,
        typer.Option("--invoice-address-enabled/--no-invoice-address-enabled", help="Enable separate invoice address"),
    ] = None,
    invoice_address: Annotated[str | None, typer.Option("--invoice-address", help="Invoice address line 1")] = None,
    invoice_address2: Annotated[str | None, typer.Option("--invoice-address2", help="Invoice address line 2")] = None,
    invoice_zip_code: Annotated[str | None, typer.Option("--invoice-zip-code", help="Invoice zip/postal code")] = None,
    invoice_city: Annotated[str | None, typer.Option("--invoice-city", help="Invoice city")] = None,
    invoice_country_code: Annotated[
        str | None, typer.Option("--invoice-country-code", help="Two-letter ISO code for invoice country")
    ] = None,
    invoice_additional_information: Annotated[
        str | None, typer.Option("--invoice-additional-information", help="Additional invoice information")
    ] = None,
    customer_category_id: Annotated[
        int | None, typer.Option("--customer-category-id", help="Customer category ID")
    ] = None,
    is_active: Annotated[
        bool | None, typer.Option("--is-active/--no-is-active", help="Whether the customer is active")
    ] = None,
    invoice_email: Annotated[str | None, typer.Option("--invoice-email", help="Email for sending invoices")] = None,
    remarks: Annotated[str | None, typer.Option("--remarks", help="Internal remarks (HTML sanitised)")] = None,
    subscription_key: Annotated[
        str | None, typer.Option("--subscription-key", "-k", envvar="QONDOR_SUBSCRIPTION_KEY")
    ] = None,
    env: Annotated[str | None, typer.Option("--env", "-e", envvar="QONDOR_ENV")] = None,
    raw: Annotated[bool, typer.Option("--raw", help="Compact JSON")] = False,
) -> None:
    """Create a customer."""
    req = CreateCustomer(
        name=name,
        office_id=office_id,
        customer_number=customer_number,
        external_reference=external_reference,
        city=city,
        country_code=country_code,
        organisation_number=organisation_number,
        legal_name=legal_name,
        address=address,
        address2=address2,
        zip_code=zip_code,
        vat_number=vat_number,
        phone_number=phone_number,
        fax_number=fax_number,
        is_invoiceable=is_invoiceable,
        invoice_currency=invoice_currency,
        invoice_currency_code=invoice_currency_code,
        invoice_address_enabled=invoice_address_enabled,
        invoice_address=invoice_address,
        invoice_address2=invoice_address2,
        invoice_zip_code=invoice_zip_code,
        invoice_city=invoice_city,
        invoice_country_code=invoice_country_code,
        invoice_additional_information=invoice_additional_information,
        customer_category_id=customer_category_id,
        is_active=is_active,
        invoice_email=invoice_email,
        remarks=remarks,
    )
    run_async(lambda c: c.customer.create(req), subscription_key=subscription_key, env=env, raw=raw)


@app.command()
def update(
    id: Annotated[int, typer.Option("--id", help="Customer ID")],
    name: Annotated[str | None, typer.Option("--name", help="Customer name")] = None,
    external_reference: Annotated[
        str | None, typer.Option("--external-reference", help="Your unique external reference")
    ] = None,
    legal_name: Annotated[str | None, typer.Option("--legal-name", help="Legal name")] = None,
    address: Annotated[str | None, typer.Option("--address", help="Address line 1")] = None,
    address2: Annotated[str | None, typer.Option("--address2", help="Address line 2")] = None,
    zip_code: Annotated[str | None, typer.Option("--zip-code", help="Zip/postal code")] = None,
    city: Annotated[str | None, typer.Option("--city", help="City")] = None,
    country_code: Annotated[str | None, typer.Option("--country-code", help="Two-letter ISO country code")] = None,
    organisation_number: Annotated[
        str | None, typer.Option("--organisation-number", help="Organisation number (may be mandatory per office)")
    ] = None,
    customer_number: Annotated[
        str | None, typer.Option("--customer-number", help="Customer number (may be autogenerated)")
    ] = None,
    vat_number: Annotated[str | None, typer.Option("--vat-number", help="VAT number")] = None,
    phone_number: Annotated[str | None, typer.Option("--phone-number", help="Phone number")] = None,
    fax_number: Annotated[str | None, typer.Option("--fax-number", help="Fax number")] = None,
    is_invoiceable: Annotated[
        bool | None, typer.Option("--is-invoiceable/--no-is-invoiceable", help="Whether the customer is invoiceable")
    ] = None,
    invoice_currency: Annotated[
        str | None, typer.Option("--invoice-currency", help="Three-letter ISO 4217 code (e.g. EUR, USD, GBP)")
    ] = None,
    invoice_currency_code: Annotated[
        int | None, typer.Option("--invoice-currency-code", help="Numeric ISO 4217 code (e.g. 978=EUR, 840=USD)")
    ] = None,
    invoice_address_enabled: Annotated[
        bool | None,
        typer.Option("--invoice-address-enabled/--no-invoice-address-enabled", help="Enable separate invoice address"),
    ] = None,
    invoice_address: Annotated[str | None, typer.Option("--invoice-address", help="Invoice address line 1")] = None,
    invoice_address2: Annotated[str | None, typer.Option("--invoice-address2", help="Invoice address line 2")] = None,
    invoice_zip_code: Annotated[str | None, typer.Option("--invoice-zip-code", help="Invoice zip/postal code")] = None,
    invoice_city: Annotated[str | None, typer.Option("--invoice-city", help="Invoice city")] = None,
    invoice_country_code: Annotated[
        str | None, typer.Option("--invoice-country-code", help="Two-letter ISO code for invoice country")
    ] = None,
    invoice_additional_information: Annotated[
        str | None, typer.Option("--invoice-additional-information", help="Additional invoice information")
    ] = None,
    customer_category_id: Annotated[
        int | None, typer.Option("--customer-category-id", help="Customer category ID")
    ] = None,
    is_active: Annotated[
        bool | None, typer.Option("--is-active/--no-is-active", help="Whether the customer is active")
    ] = None,
    invoice_email: Annotated[str | None, typer.Option("--invoice-email", help="Email for sending invoices")] = None,
    remarks: Annotated[str | None, typer.Option("--remarks", help="Internal remarks (HTML sanitised)")] = None,
    subscription_key: Annotated[
        str | None, typer.Option("--subscription-key", "-k", envvar="QONDOR_SUBSCRIPTION_KEY")
    ] = None,
    env: Annotated[str | None, typer.Option("--env", "-e", envvar="QONDOR_ENV")] = None,
    raw: Annotated[bool, typer.Option("--raw", help="Compact JSON")] = False,
) -> None:
    """Update a customer."""
    req = UpdateCustomer(
        id=id,
        name=name,
        external_reference=external_reference,
        legal_name=legal_name,
        address=address,
        address2=address2,
        zip_code=zip_code,
        city=city,
        country_code=country_code,
        organisation_number=organisation_number,
        customer_number=customer_number,
        vat_number=vat_number,
        phone_number=phone_number,
        fax_number=fax_number,
        is_invoiceable=is_invoiceable,
        invoice_currency=invoice_currency,
        invoice_currency_code=invoice_currency_code,
        invoice_address_enabled=invoice_address_enabled,
        invoice_address=invoice_address,
        invoice_address2=invoice_address2,
        invoice_zip_code=invoice_zip_code,
        invoice_city=invoice_city,
        invoice_country_code=invoice_country_code,
        invoice_additional_information=invoice_additional_information,
        customer_category_id=customer_category_id,
        is_active=is_active,
        invoice_email=invoice_email,
        remarks=remarks,
    )
    run_async(lambda c: c.customer.update(req), subscription_key=subscription_key, env=env, raw=raw)


@app.command("get-by-ref")
def get_by_ref(
    external_reference: Annotated[str, typer.Option("--external-reference", help="External reference")],
    subscription_key: Annotated[
        str | None, typer.Option("--subscription-key", "-k", envvar="QONDOR_SUBSCRIPTION_KEY")
    ] = None,
    env: Annotated[str | None, typer.Option("--env", "-e", envvar="QONDOR_ENV")] = None,
    raw: Annotated[bool, typer.Option("--raw", help="Compact JSON")] = False,
) -> None:
    """Get a customer by external reference."""
    run_async(
        lambda c: c.customer.get_by_external_reference(external_reference=external_reference),
        subscription_key=subscription_key,
        env=env,
        raw=raw,
    )


@app.command("search")
def search(
    customer_number: Annotated[str, typer.Option("--customer-number", help="Customer number to search for")],
    office_id: Annotated[int | None, typer.Option("--office-id", help="Filter by office")] = None,
    subscription_key: Annotated[
        str | None, typer.Option("--subscription-key", "-k", envvar="QONDOR_SUBSCRIPTION_KEY")
    ] = None,
    env: Annotated[str | None, typer.Option("--env", "-e", envvar="QONDOR_ENV")] = None,
    raw: Annotated[bool, typer.Option("--raw", help="Compact JSON")] = False,
) -> None:
    """Search customers by customer number."""
    run_async(
        lambda c: c.customer.get_all_by_customer_number(customer_number=customer_number, office_id=office_id),
        subscription_key=subscription_key,
        env=env,
        raw=raw,
    )
